version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/myapp_development"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0 -p 3000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
